# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
    ]
